events {}
http {
  upstream omehr_streamlit {
    least_conn;
    server web1:8501;
    server web2:8501;
  }

  server {
    listen 80;
    server_name _;
    client_max_body_size 100m;

    location / {
      proxy_pass http://omehr_streamlit;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_read_timeout 86400;
    }
  }
}
