-- OMEHR bulut panelinin yeniden kurulabilir çekirdek şeması ve kapsamlı RLS'i.
-- Railway secret/service anahtarı sunucu tarafında kalır ve bu politikaları
-- bypass ederek snapshot yazar; tarayıcı yalnız kendi yetki kapsamını okur.

create table if not exists public.omehr_user_access (
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  tenant_id text not null,
  display_name text,
  email text,
  role_code text not null default 'USER',
  region_scope text[] not null default '{}'::text[],
  store_scope text[] not null default '{}'::text[],
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (auth_user_id, tenant_id)
);

alter table public.omehr_user_access
  add column if not exists active boolean not null default true;

create table if not exists public.omehr_kpi_snapshot (
  id bigint generated by default as identity primary key,
  tenant_id text not null,
  active_current integer not null default 0,
  total_norm integer not null default 0,
  norm_deficit integer not null default 0,
  norm_surplus integer not null default 0,
  net_need integer not null default 0,
  engine_version text,
  calculated_at timestamptz not null default now()
);

create table if not exists public.omehr_store_summary (
  tenant_id text not null,
  store_id text not null,
  region_name text not null default '',
  store_name text not null,
  active_current integer not null default 0,
  total_norm integer not null default 0,
  norm_deficit integer not null default 0,
  norm_surplus integer not null default 0,
  calculated_at timestamptz not null default now(),
  primary key (tenant_id, store_name)
);

create table if not exists public.omehr_title_summary (
  tenant_id text not null,
  title_name text not null,
  active_current integer not null default 0,
  total_norm integer not null default 0,
  norm_deficit integer not null default 0,
  norm_surplus integer not null default 0,
  calculated_at timestamptz not null default now(),
  primary key (tenant_id, title_name)
);

create index if not exists omehr_user_access_user_idx
  on public.omehr_user_access (auth_user_id, tenant_id) where active;
create index if not exists omehr_kpi_snapshot_latest_idx
  on public.omehr_kpi_snapshot (tenant_id, calculated_at desc);
create index if not exists omehr_store_summary_scope_idx
  on public.omehr_store_summary (tenant_id, region_name, store_id);

alter table public.omehr_user_access enable row level security;
alter table public.omehr_kpi_snapshot enable row level security;
alter table public.omehr_store_summary enable row level security;
alter table public.omehr_title_summary enable row level security;

revoke all on public.omehr_user_access, public.omehr_kpi_snapshot,
  public.omehr_store_summary, public.omehr_title_summary from anon;
grant select on public.omehr_user_access, public.omehr_kpi_snapshot,
  public.omehr_store_summary, public.omehr_title_summary to authenticated;

drop policy if exists "users read own access" on public.omehr_user_access;
create policy "users read own access" on public.omehr_user_access
for select to authenticated
using ((select auth.uid()) = auth_user_id and active);

drop policy if exists "global users read company kpi" on public.omehr_kpi_snapshot;
create policy "global users read company kpi" on public.omehr_kpi_snapshot
for select to authenticated using (
  exists (
    select 1 from public.omehr_user_access access
    where access.auth_user_id = (select auth.uid())
      and access.tenant_id = omehr_kpi_snapshot.tenant_id and access.active
      and (
        upper(access.role_code) in ('ADMIN','HR_DIRECTOR','IK_DIREKTORU','EXECUTIVE','CEO','GM','MANAGEMENT')
        or 'ALL' = any(access.region_scope) or 'ALL' = any(access.store_scope)
      )
  )
);

drop policy if exists "scoped users read store summary" on public.omehr_store_summary;
create policy "scoped users read store summary" on public.omehr_store_summary
for select to authenticated using (
  exists (
    select 1 from public.omehr_user_access access
    where access.auth_user_id = (select auth.uid())
      and access.tenant_id = omehr_store_summary.tenant_id and access.active
      and (
        upper(access.role_code) in ('ADMIN','HR_DIRECTOR','IK_DIREKTORU','EXECUTIVE','CEO','GM','MANAGEMENT')
        or 'ALL' = any(access.region_scope) or 'ALL' = any(access.store_scope)
        or omehr_store_summary.region_name = any(access.region_scope)
        or omehr_store_summary.store_id = any(access.store_scope)
        or omehr_store_summary.store_name = any(access.store_scope)
      )
  )
);

drop policy if exists "global users read title summary" on public.omehr_title_summary;
create policy "global users read title summary" on public.omehr_title_summary
for select to authenticated using (
  exists (
    select 1 from public.omehr_user_access access
    where access.auth_user_id = (select auth.uid())
      and access.tenant_id = omehr_title_summary.tenant_id and access.active
      and (
        upper(access.role_code) in ('ADMIN','HR_DIRECTOR','IK_DIREKTORU','EXECUTIVE','CEO','GM','MANAGEMENT')
        or 'ALL' = any(access.region_scope) or 'ALL' = any(access.store_scope)
      )
  )
);

-- JSON modül snapshotları personel isimleri ve şirket geneli sonuçlar
-- içerebildiğinden satır içi bölge filtresiyle güvenli biçimde ayrılamaz.
drop policy if exists "tenant members read module snapshots" on public.omehr_module_snapshots;
drop policy if exists "global users read module snapshots" on public.omehr_module_snapshots;
create policy "global users read module snapshots" on public.omehr_module_snapshots
for select to authenticated using (
  exists (
    select 1 from public.omehr_user_access access
    where access.auth_user_id = (select auth.uid())
      and access.tenant_id = omehr_module_snapshots.tenant_id and access.active
      and (
        upper(access.role_code) in ('ADMIN','HR_DIRECTOR','IK_DIREKTORU','EXECUTIVE','CEO','GM','MANAGEMENT')
        or 'ALL' = any(access.region_scope) or 'ALL' = any(access.store_scope)
      )
  )
);

-- Satış hedefi okumasını da aynı kiracıdaki herkese açmak yerine mağaza
-- kapsamına veya şirket geneli role sınırla.
drop policy if exists "tenant members read sales targets" on public.omehr_sales_targets;
drop policy if exists "scoped users read sales targets" on public.omehr_sales_targets;
create policy "scoped users read sales targets" on public.omehr_sales_targets
for select to authenticated using (
  exists (
    select 1 from public.omehr_user_access access
    where access.auth_user_id = (select auth.uid())
      and access.tenant_id = omehr_sales_targets.tenant_id and access.active
      and (
        upper(access.role_code) in ('ADMIN','HR_DIRECTOR','IK_DIREKTORU','SATIS_DIREKTORU','SATIŞ_DİREKTÖRÜ','SALES_DIRECTOR','EXECUTIVE','CEO','GM','MANAGEMENT')
        or 'ALL' = any(access.region_scope) or 'ALL' = any(access.store_scope)
        or omehr_sales_targets.store_id = any(access.store_scope)
        or exists (
          select 1 from public.omehr_store_summary store
          where store.tenant_id = omehr_sales_targets.tenant_id
            and (store.store_id = omehr_sales_targets.store_id or store.store_name = omehr_sales_targets.store_name)
            and store.region_name = any(access.region_scope)
        )
      )
  )
);
